# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'development/Form/preview.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_preview(object):
    def setupUi(self, preview):
        preview.setObjectName("preview")
        preview.resize(555, 420)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(preview)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalFrame = QtWidgets.QFrame(preview)
        self.verticalFrame.setMinimumSize(QtCore.QSize(200, 0))
        self.verticalFrame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.verticalFrame)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.listView = QtWidgets.QListView(self.verticalFrame)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.horizontalLayout_3.addWidget(self.verticalFrame)
        self.frame_graph = QtWidgets.QFrame(preview)
        self.frame_graph.setObjectName("frame_graph")
        self.Layout_graph = QtWidgets.QVBoxLayout(self.frame_graph)
        self.Layout_graph.setObjectName("Layout_graph")
        self.horizontalLayout_3.addWidget(self.frame_graph)

        self.retranslateUi(preview)
        QtCore.QMetaObject.connectSlotsByName(preview)

    def retranslateUi(self, preview):
        _translate = QtCore.QCoreApplication.translate
        preview.setWindowTitle(_translate("preview", "Form"))
        self.pushButton.setText(_translate("preview", "Abrir Carpeta"))
