# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'development/Form/transform.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(924, 785)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.root_layout = QtWidgets.QVBoxLayout(Form)
        self.root_layout.setContentsMargins(10, 10, 10, 10)
        self.root_layout.setSpacing(10)
        self.root_layout.setObjectName("root_layout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalFrame_3 = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame_3.sizePolicy().hasHeightForWidth())
        self.horizontalFrame_3.setSizePolicy(sizePolicy)
        self.horizontalFrame_3.setObjectName("horizontalFrame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalFrame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(self.horizontalFrame_3)
        self.label.setMinimumSize(QtCore.QSize(74, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.btn_open = QtWidgets.QPushButton(self.horizontalFrame_3)
        self.btn_open.setMinimumSize(QtCore.QSize(105, 0))
        self.btn_open.setObjectName("btn_open")
        self.horizontalLayout_7.addWidget(self.btn_open)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addWidget(self.horizontalFrame_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalFrame = QtWidgets.QFrame(Form)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_8.setContentsMargins(-1, 1, -1, -1)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalFrame_2 = QtWidgets.QFrame(self.verticalFrame)
        self.horizontalFrame_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.horizontalFrame_2.setObjectName("horizontalFrame_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalFrame_2)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_3 = QtWidgets.QLabel(self.horizontalFrame_2)
        self.label_3.setMinimumSize(QtCore.QSize(0, 20))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_10.addWidget(self.label_3)
        self.verticalLayout_8.addWidget(self.horizontalFrame_2)
        self.horizontalFrame = QtWidgets.QFrame(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame.sizePolicy().hasHeightForWidth())
        self.horizontalFrame.setSizePolicy(sizePolicy)
        self.horizontalFrame.setMaximumSize(QtCore.QSize(600, 16777215))
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.Table_layout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.Table_layout.setContentsMargins(0, 0, 0, 0)
        self.Table_layout.setSpacing(0)
        self.Table_layout.setObjectName("Table_layout")
        self.verticalLayout_8.addWidget(self.horizontalFrame)
        self.horizontalLayout.addWidget(self.verticalFrame)
        self.verticalFrame1 = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalFrame1.sizePolicy().hasHeightForWidth())
        self.verticalFrame1.setSizePolicy(sizePolicy)
        self.verticalFrame1.setMinimumSize(QtCore.QSize(0, 200))
        self.verticalFrame1.setObjectName("verticalFrame1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalFrame1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalFrame1 = QtWidgets.QFrame(self.verticalFrame1)
        self.horizontalFrame1.setMaximumSize(QtCore.QSize(16777215, 20))
        self.horizontalFrame1.setObjectName("horizontalFrame1")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalFrame1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.horizontalFrame1)
        self.label_6.setMinimumSize(QtCore.QSize(0, 20))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.verticalLayout_4.addWidget(self.horizontalFrame1)
        self.verticalFrame2 = QtWidgets.QFrame(self.verticalFrame1)
        self.verticalFrame2.setObjectName("verticalFrame2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalFrame2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_4.addWidget(self.verticalFrame2)
        self.horizontalLayout.addWidget(self.verticalFrame1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.root_layout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalFrame_4 = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame_4.sizePolicy().hasHeightForWidth())
        self.horizontalFrame_4.setSizePolicy(sizePolicy)
        self.horizontalFrame_4.setObjectName("horizontalFrame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalFrame_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3.addWidget(self.horizontalFrame_4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_2 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalFrame_8 = QtWidgets.QFrame(Form)
        self.horizontalFrame_8.setObjectName("horizontalFrame_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.horizontalFrame_8)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.horizontalFrame_8)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.verticalWidget_3 = QtWidgets.QWidget(self.horizontalFrame_8)
        self.verticalWidget_3.setObjectName("verticalWidget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.verticalWidget_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.v1 = QtWidgets.QVBoxLayout()
        self.v1.setObjectName("v1")
        self.horizontalLayout_5.addLayout(self.v1)
        self.v2 = QtWidgets.QVBoxLayout()
        self.v2.setContentsMargins(0, -1, -1, -1)
        self.v2.setObjectName("v2")
        self.horizontalLayout_5.addLayout(self.v2)
        self.verticalLayout_7.addWidget(self.verticalWidget_3)
        self.horizontalLayout_2.addWidget(self.horizontalFrame_8)
        self.verticalFrame_2 = QtWidgets.QFrame(Form)
        self.verticalFrame_2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.verticalFrame_2.setObjectName("verticalFrame_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalFrame_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalFrame_9 = QtWidgets.QFrame(self.verticalFrame_2)
        self.horizontalFrame_9.setMaximumSize(QtCore.QSize(16777215, 20))
        self.horizontalFrame_9.setObjectName("horizontalFrame_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalFrame_9)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.horizontalFrame_9)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalFrame_9)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_8.addWidget(self.pushButton_2)
        self.verticalLayout_5.addWidget(self.horizontalFrame_9)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.verticalFrame_2)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 248, 333))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents_2)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_10.addWidget(self.plainTextEdit)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_9.addWidget(self.scrollArea_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_9)
        self.horizontalLayout_2.addWidget(self.verticalFrame_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.root_layout.addLayout(self.verticalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Etapa 1"))
        self.btn_open.setText(_translate("Form", "Paso 1 : Abrir"))
        self.label_3.setText(_translate("Form", "Paso 2: revisar"))
        self.label_6.setText(_translate("Form", "Paso 3: Actualizar Datos"))
        self.label_2.setText(_translate("Form", "Etapa 2"))
        self.label_4.setText(_translate("Form", "Paso 4: Revisar Gráfico"))
        self.label_5.setText(_translate("Form", "Paso 5: verificar *.json"))
        self.pushButton_2.setText(_translate("Form", "y Guardar"))

