self.frame_win_bar.setStyleSheet(u"QFrame{background-color: rgb(61, 64, 77)}\n"
                                         "\n"
                                         "QPushButton{\n"
                                         "	padding-top: 5px;\n"
                                         "	background-color: rgb(84, 89,105); \n"
                                         "	color:rgb(209,210,214);\n"
                                         "	border:none; \n"
                                         "	border-top-right-radius:5px;\n"
                                         "	border-top-left-radius:5px;\n"
                                         "}\n"
                                         "QPushButton#btn_menu{\n"
                                         "	background-color: rgb(73, 102,153); \n"
                                         "}\n"
                                         "\n"
                                         "QPushButton#btn_min, QPushButton#btn_max{\n"
                                         "	background-color:rgba(81,83,95,0);\n"
                                         "	padding-top: 0px;\n"
                                         "	border:none;\n"
                                         "	border-top-right-radius:0px;\n"
                                         "	border-top-left-radius:0px;\n"
                                         "}\n"
                                         "QPushButton#btn_min:hover, QPushButton#btn_max:hover{background-color:rgb(81,83,95)}\n"
                                         "\n"
                                         "QPushButton#btn_exit{\n"
                                         "	padding-top: 0px;\n"
                                         "	border:none;\n"
                                         "	border-top-right-radius:0px;\n"
                                         "	border-top-left-radius:0px;\n"
                                         "	background-color: rgba(73, 102,153,0);\n"
                                         "}\n"
                                         "QPushButton#btn_exit:hover{background-color: rgb(240, 96,77);}\n"
                                         "QPushButton#btn_new{background-color: rgba(73, 102,153,0);}\n"
                                         "QPushButton:pressed{\n"
                                         "	background-color: rgb(232,232,232); \n"
                                         "	color:rgb(95,145"
                                         ",230)\n"
                                         "}\n"
                                         "QPushButton#btn_menu:checked{\n"
                                         "	background-color: rgb(245, 245,245); \n"
                                         "	color:rgb(95,145,230)\n"
                                         "}\n"
                                         "\n"
                                         "QTabBar{\n"
                                         "    border-top: 30px solid #3d404d;\n"
                                         "    background-color: rgb(245,245,245);\n"
                                         "    qproperty-drawBase:0;\n"
                                         "    }\n"
                                         "\n"
                                         "QTabBar::tab {\n"
                                         "    border: 1px solid #3d404d;\n"
                                         "    background: rgb(84,89,105);\n"
                                         "	color:rgb(209,210,214);\n"
                                         "    border-top-left-radius: 5px;\n"
                                         "    border-top-right-radius: 5px;\n"
                                         "    border-bottom : none;\n"
                                         "    padding-left: 5px;\n"
                                         "    padding-right: 5px;\n"
                                         "}\n"
                                         "QTabBar::tab:tear {\n"
                                         "        border-bottom : none;\n"
                                         "        padding: 7 20px;\n"
                                         "}\n"
                                         "QTabBar::tab:selected:active {\n"
                                         "    background: rgb(232,232,232);\n"
                                         "    color:rgb(95,145,230)\n"
                                         "}\n"
                                         "QTabBar::tab:hover{background: rgb(107,114,132);}\n"
                                         "QTabBar::close-button:hover {background: rgb(107,114,132);}")